stages:
    - build
    
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "leila1378" -p "fakheri1378"
  script:
    - docker build -t myapp .
    # - docker run -d 8080:8080 "$CI_REGISTRY_IMAGE"
    - docker push myapp
  only:
    - master

# stages:
#     - build

# build:
#     stage: build
#     script:
#         - echo "building..." 
#         - docker build -t myapp .
#         - docker run -d 8080:8080 myapp
#         - 