docker-build: 
  before_script: 
    - "docker login -u \"leila1378\" -p \"fakheri1378\""
  connect: 
    image: mysql
    script: 
      - "echo \"SELECT 'OK';\" | mysql --user=root --password=\"$MYSQL_ROOT_PASSWORD\" --host=mysql \"$MYSQL_DATABASE\""
  image: "docker:latest"
  only: 
    - master
  script: 
    - "docker build -t \"index.docker.io/leila1378/loghmeh\" ."
    - "docker push \"index.docker.io/leila1378/loghmeh\""
  services: 
    - "mysql:latest"
    - "docker:dind"
  stage: build
  variables: 
    MYSQL_DATABASE: loghmeh
    MYSQL_ROOT_PASSWORD: yaali121
stages: 
  - build
