apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3306
      targetPort: 3306
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "300Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: mahya-leila-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: "380Mi"
              cpu: "200m"
            requests:
              memory: "280Mi"
              cpu: "200m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yaali121

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
